### ISSUE TITLE
GitHubError: 422 Validation Failed

### ISSUE THREAD

**Issue by benjamindeleener** [plotly/octogrid#3]
Hi I am trying to use octogrid but I've got a ```github3.models.GitHubError: 422 Validation Failed``` error. See full terminal result below:
```
bendeleener:~ $ octogrid generate --user=benjamindeleener
You need to be logged in to use octogrid.
Enter Your GitHub Username: benjamindeleener
Password for benjamindeleener: 
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/octogrid", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python2.7/site-packages/octogrid/octogrid.py", line 23, in main
    parser.action()
  File "/usr/local/miniconda/lib/python2.7/site-packages/octogrid/parser/parser.py", line 26, in action
    generate_network(user, reset)
  File "/usr/local/miniconda/lib/python2.7/site-packages/octogrid/generator/generator.py", line 34, in generate_network
    token = collect_token()
  File "/usr/local/miniconda/lib/python2.7/site-packages/octogrid/generator/generator.py", line 24, in collect_token
    previous_token = authenticate()
  File "/usr/local/miniconda/lib/python2.7/site-packages/octogrid/auth/auth.py", line 53, in authenticate
    raise e
github3.models.GitHubError: 422 Validation Failed
```

Any idea why octogrid does not want to work with me?

**Comment by pravj** [comment]
Hi @benjamindeleener,

This seems like an issue with updating "auth token".

Can you help me reproducing this?
I'm observing the same error when I manually remove the credential file (~/.octogrid/.octogrid), let me know if you can tell me the steps that landed you here.

In that case, deleting the "personal access token" for octogrid is working for me.
![possible-solution](http://i.imgur.com/4iMNcwj.png)

Thanks for reporting, I'm looking into this.

**Comment by benjamindeleener** [comment]
Hi @pravj 
I removed the "command line tool ..." token and it gets a little further, but still failing. Actually, I don't seem to have a ```~/.octogrid/``` folder

Here are the results:
```
bendeleener:~ $ octogrid generate --user=benjamindeleener
You need to be logged in to use octogrid.
Enter Your GitHub Username: benjamindeleener
Password for benjamindeleener: 
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/octogrid", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python2.7/site-packages/octogrid/octogrid.py", line 23, in main
    parser.action()
  File "/usr/local/miniconda/lib/python2.7/site-packages/octogrid/parser/parser.py", line 26, in action
    generate_network(user, reset)
  File "/usr/local/miniconda/lib/python2.7/site-packages/octogrid/generator/generator.py", line 34, in generate_network
    token = collect_token()
  File "/usr/local/miniconda/lib/python2.7/site-packages/octogrid/generator/generator.py", line 24, in collect_token
    previous_token = authenticate()
  File "/usr/local/miniconda/lib/python2.7/site-packages/octogrid/auth/auth.py", line 55, in authenticate
    with open(credentials_file, 'w') as f:
IOError: [Errno 2] No such file or directory: '/Users/benjamindeleener/.octogrid/.octogrid'
```

**Comment by pravj** [comment]
@benjamindeleener, do you mind upgrading your version of octogrid?
> sudo pip install octogrid --upgrade

I have implemented a fix for the issue.

One more time, you need to remove the "personal access token" for "octogrid" from all your [tokens](https://github.com/settings/tokens) and it should work fine.

I will think about this particular problem when the octogrid GitHub application is created (already authenticated) and we try to authenticate nonetheless, it was [known](https://github.com/plotly/octogrid/blob/master/octogrid/generator/generator.py#L21) to me but I didn't find the documentation good enough like web applications using GitHub OAuth.

**Comment by benjamindeleener** [comment]
Works great now. Thank you!

**Comment by pravj** [comment]
Cool, I'm going to miss my morning classes (probably), but good to see this getting fixed.

Thanks again for reporting the issue. Happy Plotting.
